### ISSUE TITLE
Insecure "salt" use.

### ISSUE THREAD

**Issue by amcgregor** [Levantado/Flask-Argonaut#1]
Howdy!

Was searching around for Argonaut implementations, found this integration, then was immediately alarmed when I read "Salt may set in app with environment settings…" — this defeats the purpose of adding salt by being constant for the application, for all hashed passwords, allowing a targeted rainbow table to be constructed, instead of varying the salt from password to password to make rainbow table use impossible.  (The purpose of salting.)

For details, please see the ["Short Salt & Salt Reuse" section of this article](https://crackstation.net/hashing-security.htm#salt), or this [auth0.com article](https://auth0.com/blog/adding-salt-to-hashing-a-better-way-to-store-passwords/), or [Salted Password Hashing - Doing It Right](https://www.codeproject.com/Articles/704865/Salted-Password-Hashing-Doing-it-Right), or the [password storage cheat-sheet section on "use a cryptographically strong credential-specific salt"](https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet#Use_a_cryptographically_strong_credential-specific_salt), or [point 3 of the recap of this article](https://blog.codinghorror.com/youre-probably-storing-passwords-incorrectly/).

Thanks!

**Comment by Levantado** [comment]
Thank you. I remove it from release.
